### PR TITLE
Create ru.po

### PR DESCRIPTION
**Pull request by Anatoliy6463**
Also, change description to "Free(as in freedom)" instead of "Open source", because it think, free(as in freedom) gives more freedom for users. gnu.org fsf.org

### CODE REVIEW

**Comment by Anatoliy6463** [comment]
Also added gun 3D model that i made some minutes ago, it's simple, yet good

**Comment by Lulu-Games** [comment]
Is it a Paintball Gun?

**Comment by Anatoliy6463** [comment]
Yeah, a gun and Russian language (stub)

**Comment by Anatoliy6463** [comment]
People from Russia love games, but some of them don't know English, so, we need to add the Russian language to this game, also, I can add French language and Arabish

**Comment by Lulu-Games** [comment]
But use the Translator.py instead of po files

**Comment by Lulu-Games** [comment]
And upload the translations directly to the data repos

**Comment by Lulu-Games** [comment]
This isn't a paintball gun! I mean the ones like this
[PaintballShooter.zip](https://github.com/SpringTech-Studios/SisijaFight/files/13977078/PaintballShooter.zip)

**Comment by Anatoliy6463** [comment]
And... It's a prototype, not final product

**Comment by Lulu-Games** [comment]
Ok

**Comment by Anatoliy6463** [comment]
Will you commit to Andesaurux?

**Comment by Anatoliy6463** [comment]
But first, write about changes in Andesaurux-Chat

**Comment by Lulu-Games** [comment]
Yes maybe

**Comment by Anatoliy6463** [comment]
> But use the Translator.py instead of po files

What do i need to do with this file?

**Comment by Lulu-Games** [comment]
It is a qt interface to create json translation files. You need to run it in the src folder (with ALL cpps)

**Comment by Lulu-Games** [comment]
To run you have to install Python and run "pip install PyQt6" or if you use Windows, run the STRANSLATOR.exe

**Comment by Anatoliy6463** [comment]
> To run you have to install Python and run "pip install PyQt6" and then run the Translator.py or if you use Windows, run the STRANSLATOR.exe

OK

**Pull request closed without merging**
